### PR TITLE
Fix/batch option validation

### LINKED ISSUE #35: Options validation not working for batch mode
Currently, any required options for a batch runner will cause a validation error whether those options are passed or not.

I think the options are not being passed to the validation function.  I can try to do this when I get some time.

### PR DESCRIPTION
**Pull request by stephan-noel**
# Description

There is an extra unneccessary (and incorrect) validation for batch handlers, causing them to fail validation.

Fixes #35

## How Has This Been Tested?

Did the fix in node_modules.  Ensured that the fix does validation correctly on required properties. 
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests to cover my changes
- [x] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: core/garment/src/garment.ts [hunk 1]
```diff
@@ -1037,8 +1037,6 @@ async function garmentFromWorkspace(
         ...restRunners[runner.name]
       };
 
-      validateOptions(runner, options);
```
Comment (stephan-noel) [inline core/garment/src/garment.ts:1040]: @beshanoe The `validateOptions` invocation in the pic below seems to correctly validate both batch and non-batch handlers.  Can you see any reason for having validation in `runActionsInBatch` as well?  The options it is passing here do not have the options for each project, since those options are inside the batch variable.  That's why it's failing. 
image

Comment (beshanoe) [reply core/garment/src/garment.ts:1040]: yeah, seems your right, all of those options are already merged in the `getActionGraph` and then validated in this place, so another place seems redundant(and also erroneous)

**Review by beshanoe — APPROVED** [review]

**Comment by beshanoe** [comment]
@stephan-noel also, great addition to the docs!
