### PR TITLE
fix: Files flag #37

### LINKED ISSUE #37: Garment eslint-runner is only running on a single file of each project when running with --files option
In our project, we use garment to show errors on precommit and we noticed that instead of showing all the errors it was showing only one error per project.

By doing two errors in the same project when we run 
```
$ yarn garment lint project-1
yarn run v1.17.3
$ /Users/XXX/projects/XXX/node_modules/.bin/garment lint project-name-1
🧤 Garment v0.14.3


Projects in progress:
 HAS ERRORS  Project project-name-1 2 subtasks done

eslint error
             /Users/XXX/projects/XXX/project/name-1/src/layout/app.js
               55:19  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
               1 error and 0 warnings potentially fixable with the `--fix` option.

eslint error
             /Users/XXX/projects//XXX/project/name-1/src/modules/form/Form.js
               117:22  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
               1 error and 0 warnings potentially fixable with the `--fix` option.

Projects: 1 total
Tasks:    2 total

error Error: One or more errors occured during runners execution
          at handler (/Users/XXX/projects/XXX/node_modules/@garment/cli/lib/defaults.js:177:15)
          at async Object.handler (/Users/XXX/projects/XXX/node_modules/@garment/cli/lib/defaults.js:183:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

and then by running it with --files option containing both files that have eslint problems it only shows one of the errors

```
$ yarn garment lint --files /Users/XXX/projects/XXX/project/name-1/src/layout/app.js /Users/XXX/projects/XXX/project/name-1/src/modules/form/Form.js
yarn run v1.17.3
$ /Users/XXX/projects/XXX/node_modules/.bin/garment lint --files /Users/XXX/projects/XXX/project/name-1/src/layout/app.js /Users/XXX/projects/XXX/project/name-1/src/modules/form/Form.js
🧤 Garment v0.14.3

 HAS ERRORS  Project project-name-1 1 subtasks done

eslint error
             /Users/XXX/projects/XXX/project-name-1/src/layout/app.js
               55:19  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
               1 error and 0 warnings potentially fixable with the `--fix` option.

Projects: 1 total
Tasks:    1 total

error Error: One or more errors occured during runners execution
          at handler (/Users/XXX/projects/XXX/node_modules/@garment/cli/lib/defaults.js:177:15)
          at async Object.handler (/Users/XXX/projects/XXX/node_modules/@garment/cli/lib/defaults.js:183:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can someone help me 🙏 ?

### PR DESCRIPTION
**Pull request by beshanoe**
# Description

It turned out that the function `getProjectsByName` would only allow passing one matched file by project. I've fixed that and also I removed the part where the function had 2 different types of return. I had to change other places which expected 2 different types

Fixes #37

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have added tests to cover my changes
- [x] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: core/workspace/src/Project.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ class ClassMap extends Map<Constructor<any>, any> {
 }
 
 export class Project {
+  readonly isProject = true;
```
Comment (joaopedrodcf) [inline core/workspace/src/Project.ts]: From what I saw this variable is not used anywhere should we had it to the class Project?

Comment (beshanoe) [reply core/workspace/src/Project.ts]: good point! removed
