### PR TITLE
fix: Workspace path match

### LINKED ISSUE #24: Garment finds incorrect project with files option when there are projects with similar names
## Issue Report

I have two projects in my monorepo section-product and section-product-carousel.  When I do `garment lint - - files <workspace_root>\section\product-carousel\src\modules\product-carousel\ProductCarousel.js` the actionGraph is empty and so nothing is executed.  

## Expected Behavior

It should return the correct project, section-product-carousel and execute the task.  Both getPath and getPaths probably should be changed to make sure it only checks complete segments of the path.

## Actual Behavior

I traced the problem to this method.

image

It returns section-product as the project associated with the file instead of section-product-carousel because technically they both start with the file path.  When I debugged and changed it to the correct project, the task executed properly.

## Steps to Reproduce the Issue

Have two projects in which the path of one is a substring of the other.

I can take this and add some unit tests for projectRegistry.

### PR DESCRIPTION
**Pull request by opcode0x**
# Description

Change the way of detection if file belongs to project.

Fixes #24 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes
- [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: core/utils/src/isSubPath/index.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import path = require('path');
```
Comment (beshanoe) [inline core/utils/src/isSubPath/index.ts]: let's use more conventional(in this project) `import * as Path from "path"` or `import { relative } from "path"`
