### PR TITLE
fix: Invoke destroy handler in batch mode

### LINKED ISSUE #31: Batch mode does not trigger longRunning onDestroy handlers
## Issue Report

Garment is not invoking the onDestroy handlers when a batch runner finishes executing.

## Expected Behavior

Garment should invoke onDestroy handlers when the first non longRunning task is in batch mode as well.

## Actual Behavior

In the following config , runner-wdio is run in batch mode.  When it ends however, runner-docker-compose and runner-web-scripts: serve (both which use context.longRunning), do not have their onDestroy handlers invoked.

image

### PR DESCRIPTION
**Pull request by opcode0x**
# Description

Invoke destroy handler for project dependent tasks after batch task was finished.

Fixes #31 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests to cover my changes
- [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: core/garment/src/garment.ts [hunk 1]
```diff
@@ -895,6 +895,12 @@ async function garmentFromWorkspace(
       watch: true,
       runnerOptions
     });
+  } else {
+    if (!watcherStarted) {
+      for (const meta of metaByAction.values()) {
+        meta?.onDestroyHandler?.();
```
Comment (stephan-noel) [inline core/garment/src/garment.ts:906]: I logged meta here for some batch actions and they didn't have an `onDestroyHandler`.

I put the following code in `runActionsInBatch` and it seemed to work, what do you think?:

image

image

Comment (opcode0x) [reply core/garment/src/garment.ts:906]: lgtm, @beshanoe what do you think?

Comment (beshanoe) [reply core/garment/src/garment.ts:906]: @stephan-noel I dont get why would you assign a to the batchMeta the first encountered action's meta? probably you can assign there only a batch's onDestroyHandler? Can you please push into this PR a whole solution?

Comment (stephan-noel) [reply core/garment/src/garment.ts:906]: @beshanoe  you're right, I was only considering my own use case in which I need `context.longRunning` to only be called once per runner.  

I guess maybe there are several approaches here:
- Call `context.longRunning` once per runner (NOT per project per runner) like I do above.  If you want to handle shutdown for several projects, you can do something like (ignore the invocation of onetime below) :

image

- Call context.longRunning once per action (the approach you were expecting of per project per runner), and if the cleanup had already been done by a previous project (ie, the projects shared the same port and I already closed it), then I have to detect that it was already cleaned up or limit it the invocations somehow.

Honestly the first approach seemed more natural to me, but I may be biased to my use case, what are your thoughts?

Comment (stephan-noel) [reply core/garment/src/garment.ts:906]: @beshanoe Changed it a bit to separate the non-batch meta from batchMeta.  I do set and get for batchMetaByAction where I do to bring attention to the fact that having one meta per action instead of per runner is a possibility in the future.  What do you think?
